### ISSUE TITLE
Object maps are empty after opening a new tab

### ISSUE THREAD

**Issue by IzGiulio** [wobsoriano/pinia-shared-state#16]
Hello, in my application I have a shared object having some Maps which are fulfilled inside its constructor. When I work with a single tab, everything is fine, the object is created with its mappers. However, when I open a second tab, which will recreate this object and save it again in the store,  the mappers of the first tab are empty. I have this problem only with the mappers, every other attribute is fine.

I created a small example:

```
export class User {
    id: string
    name: string

    constructor(id: string, name: string) {
        this.id = id
        this.name = name
    }
}

```

The following class is the one creating the mapper inside its constructor:
```
import {User} from "./User";

export class Data {
    private idToUser = new Map<string, User>()
    private userLength: number

    constructor(users: User[]) {
        users.forEach(user => this.idToUser.set(user.id, user))
        this.userLength = users.length
    }
}

```
Store: 
```
import {defineStore} from "pinia";
import {Service} from "./Service";
import {Data} from "./Data";

interface StoreInterface {
    data: undefined | Data
}

export const useStore = defineStore('store', {
    state: (): StoreInterface => ({
        data: undefined
    }),
    actions: {
        getData() {
            this.data = Service.getData()
        }
    }
})
```

Service:
```
import {Data} from "./Data";
import {User} from "./User";

export class Service {

    static getData() {
        return new Data([
            new User('1', 'Spike'),
            new User('2', 'Valentine')
        ])
    }
}
```

main.ts: 

```
createApp(App).use(createPinia()
    .use(PiniaSharedState({enable: true, initialize: false})))
    .mount('#app')
```

And then its usage inside the component:

```
export default defineComponent({
  name: "DataComponent",
  setup() {
    const store = useStore()
    const {data} = storeToRefs(store)

    onMounted(() => {
      if (store.data === undefined) {
        store.getData()
      }
    })

    return {data}
  }
})
```
Results:

When I open one tab everything is fine:
![Screenshot from 2022-09-18 10-52-18](https://user-images.githubusercontent.com/57524406/190893988-6543dcc7-73a7-4a35-b4ad-b14a0a24efe7.png)

When I open a second tab, the map inside the object of the first tab is empty:
![Screenshot from 2022-09-18 10-52-26](https://user-images.githubusercontent.com/57524406/190893983-96cae157-5df8-444c-b11b-b6315c941042.png)

**Comment by wobsoriano** [comment]
Fixed in https://github.com/wobsoriano/pinia-shared-state/releases/tag/v0.2.9

**Comment by wazolab** [comment]
I'm still facing the same issue on v0.5.1, @IzGiulio do you confirm the fix on your side ??
Thx
